update uptimerobotcronjob
Former-commit-id: f09cd4027f7bd78b059eadd42f5d9b499b9d2f65 [formerly ab49f2798ceb444ad47f9c72d0f12430cf5ec47b] [formerly 3fe209bae0316462b2a845eb85f232a0ce22aa12 [formerly 925a1c4ebeb9c9d79aea3f7a952c037d56631457]]
Former-commit-id: 17baba6d4ce691e08059a07eef60edf5194ad4e3 [formerly c73e0ce06b35d3f3b7f07499aa9c0e197ec2c76b]
Former-commit-id: 12c716735b2e5224794a83db62200b992bafa4bb

diff --git a/deployments/monitoring/uptimerobot-heartbeat.yaml b/deployments/monitoring/uptimerobot-heartbeat.yaml
--- a/deployments/monitoring/uptimerobot-heartbeat.yaml
+++ b/deployments/monitoring/uptimerobot-heartbeat.yaml
@@ -12,11 +12,29 @@ spec:
         spec:
           containers:
           - name: uptimerobot-heartbeat
-            image: onedr0p/healthcheck:v1.0.0
+            image: curlimages/curl:7.70.0
+            imagePullPolicy: IfNotPresent
             env:
               - name: HEALTHCHECK_URL
                 valueFrom:
                   secretKeyRef:
                     name: uptimerobot-heartbeat
                     key: url
+            command:
+              - "/bin/sh"
+              - "-ec"
+              - |
+                set -o nounset
+                set -o errexit
+                if [[ -z "${HEALTHCHECK_URL}" ]]; then
+                    echo "$(date -u) - Error - Missing HEALTHCHECK_URL environment variable"
+                    exit 1
+                fi
+                status_code=$(curl -I -s -o /dev/null -w '%{http_code}' ${HEALTHCHECK_URL})
+                if [[ ! "${status_code}" =~ ^(2[[:digit:]]{2})$ ]]; then
+                    echo "$(date -u) - ERROR - Heartbeat request failed, http code: ${status_code}"
+                    exit 1
+                fi
+                echo "$(date -u) - Success - Heartbeat request received and processed successfully"
+                exit 0
           restartPolicy: OnFailure
