update uptimerobotcronjob

diff --git a/deployments/monitoring/uptimerobot-heartbeat.yaml b/deployments/monitoring/uptimerobot-heartbeat.yaml
--- a/deployments/monitoring/uptimerobot-heartbeat.yaml
+++ b/deployments/monitoring/uptimerobot-heartbeat.yaml
@@ -26,15 +26,15 @@ spec:
               - |
                 set -o nounset
                 set -o errexit
-                if [[ -z "${HEALTHCHECK_URL}" ]]; then
-                    echo "$(date -u) - Error - Missing HEALTHCHECK_URL environment variable"
-                    exit 1
+                if [ -z "${HEALTHCHECK_URL}" ]; then
+                  printf "%s - Error - Missing HEALTHCHECK_URL environment variable" "$(date -u)"
+                  exit 1
                 fi
-                status_code=$(curl -I -s -o /dev/null -w '%{http_code}' ${HEALTHCHECK_URL})
-                if [[ ! "${status_code}" =~ ^(2[[:digit:]]{2})$ ]]; then
-                    echo "$(date -u) - ERROR - Heartbeat request failed, http code: ${status_code}"
-                    exit 1
+                status_code=$(curl -I -s -o /dev/null -w '%{http_code}' "${HEALTHCHECK_URL}")
+                if [ "${status_code}" != 200 ]; then
+                  printf "%s - ERROR - Heartbeat request failed, http code: %s" "$(date -u)" "${status_code}"
+                  exit 1
                 fi
-                echo "$(date -u) - Success - Heartbeat request received and processed successfully"
+                printf "%s - Success - Heartbeat request received and processed successfully" "$(date -u)"
                 exit 0
           restartPolicy: OnFailure
